# Generated by Django 5.2.2 on 2025-06-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=225)),
                ('tittle', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=450)),
            ],
        ),
    ]
