# Generated by Django 5.2.2 on 2026-01-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='tittle',
            new_name='title',
        ),
    ]
